services:
  go-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: go_dev_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    tty: true
